<template>
  <v-app>
    <main>
      <v-content>
        <v-layout justify-center column my-4>
          <v-flex>
            <v-card flat class="pg-v-card">
              <v-card-text class="pg-v-card-text-main">
                 How it works
              </v-card-text>
            </v-card>
            </v-flex>
          <v-flex>
            <v-card flat class="pg-v-card-bottom">
                <v-card-text class="pg-v-card-text-small">
                  <p>
                    <b> The Performance Farm </b> <br>
                    Postgres Performance Farm is a web interface to interact with users' test results, generated by the Django API.
                  </p>
                  <br>
                  <p>
                    <b> Login </b> <br>
                    Login is allowed with the same credentials inserted in the Django API, produced via command line.
                  </p>
                  <br>
                  <p>
                    <b> Status </b> <br>
                    The Status page displays the latest status of each farm member, for each branch it has reported on in the last 30 days.
                  </p>
                  <br>
                  <p>
                    <b> Machine </b> <br>
                    The Machine page displays a summary of all machines, which can be selected to see further details and recent tests.
                  </p>
                  <br>
                  <p>
                    <b> Django API </b> <br>
                    Information about the Django API and its setup can be found on the related <u> <a href='https://github.com/PGPerfFarm/pgperffarm' target="_blank">GitHub repository</a></u>.
                  </p>
                </v-card-text>
          </v-card>
          </v-flex>
       </v-layout>
      </v-content>
    </main>
  </v-app>
</template>

<script>

  export default {
    name: 'help'
  }
</script>
