# Generated by Django 3.2.13 on 2022-05-07 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostgresSettingsSet',
            fields=[
                ('postgres_settings_set_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('settings_sha256', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostgresSettings',
            fields=[
                ('postgres_settings_id', models.AutoField(primary_key=True, serialize=False)),
                ('setting_name', models.TextField()),
                ('setting_unit', models.TextField(null=True)),
                ('setting_value', models.TextField(blank=True, null=True)),
                ('db_settings_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='postgres.postgressettingsset')),
            ],
            options={
                'unique_together': {('db_settings_id', 'setting_name')},
            },
        ),
    ]
