# Generated by Django 3.2.13 on 2023-06-16 05:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('runs', '0002_runinfo_benchmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplainQueryCostOffPlan',
            fields=[
                ('hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('result', models.JSONField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ExplainQueryCostOnResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning_time', models.FloatField()),
                ('execution_time', models.FloatField()),
                ('planning', models.JSONField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='TpchConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scale_factor', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('streams', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TpchQuery',
            fields=[
                ('query_id', models.SmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('query_statement', models.CharField(default=None, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='TpchResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('power_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('throughput_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('composite_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('benchmark_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpch.tpchconfig')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.runinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TpchQueryResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.FloatField()),
                ('type', models.CharField(max_length=30)),
                ('query_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpch.tpchquery')),
                ('tpch_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpch.tpchresult')),
            ],
        ),
        migrations.CreateModel(
            name='ExplainQueryCostOnResultDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField()),
                ('explain_query_cost_on_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpch.explainquerycostonresult')),
            ],
        ),
        migrations.AddField(
            model_name='explainquerycostonresult',
            name='tpch_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpch.tpchquery'),
        ),
        migrations.AddField(
            model_name='explainquerycostonresult',
            name='tpch_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpch.tpchresult'),
        ),
        migrations.CreateModel(
            name='ExplainQueryCostOffResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_hash', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tpch.explainquerycostoffplan')),
                ('tpch_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpch.tpchqueryresult')),
            ],
        ),
    ]
