# Generated by Django 3.2.13 on 2023-07-09 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpch', '0002_tpchqueryresult_query_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explainquerycostonresult',
            name='planning',
        ),
    ]
