# Generated by Django 3.2.13 on 2023-05-06 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('alias', models.CharField(default='', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('machine_secret', models.CharField(default='', max_length=128, unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('machine_type', models.CharField(blank=True, default='', max_length=100)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('add_time',),
            },
        ),
    ]
